name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: github_actions
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.6]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env: 
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        API_KEY: ${{ secrets.API_KEY }}
        USERNAME: ${{ secrets.USERNAME }}
        SENDER: ${{ secrets.SENDER }}
        
        DATABASE_NAME: github_actions
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432  # PostgreSQL's default port
        
        DEBUG: ${{ secrets.DEBUG }}
      run: |
        python manage.py test
